#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'gosu'
require 'pry'
require 'zeitwerk'

loader = Zeitwerk::Loader.new
loader.enable_reloading
loader.push_dir('config')
loader.push_dir('lib/constants')
loader.push_dir('lib/engines')
loader.push_dir('lib/services')
loader.push_dir('lib/util')
loader.push_dir('lib/views')
loader.push_dir('lib/rules')
loader.push_dir('lib/objects')
loader.setup

# You can add fixtures and/or initialization code here to make experimenting
# with your gem easier. You can also use a different console, if you like.

# (If you use this, don't forget to add pry to your Gemfile!)
# require "pry"
# Pry.start

require 'irb'
IRB.start(__FILE__)
