#!/usr/bin/env ruby
# frozen_string_literal: true

require 'gosu'
require 'dry-initializer'
require 'memoist'
require 'pry'
require 'zeitwerk'

loader = Zeitwerk::Loader.new
loader.push_dir('config')
loader.push_dir('lib/constants')
loader.push_dir('lib/engines')
loader.push_dir('lib/services')
loader.push_dir('lib/util')
loader.push_dir('lib/views')
loader.push_dir('lib/rules')
loader.push_dir('lib/objects')
loader.setup
loader.eager_load

Window.new.show
